# Generated by Django 5.2.8 on 2025-11-24 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Maquinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('tipo', models.CharField(max_length=100)),
                ('fecha_adquisicion', models.DateField()),
                ('estado', models.CharField(choices=[('operativa', 'Operativa'), ('en_reparacion', 'En reparación'), ('fuera_servicio', 'Fuera de servicio')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('stock', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Mantencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('preventiva', 'Preventiva'), ('correctiva', 'Correctiva'), ('predictiva', 'Predictiva')], max_length=50)),
                ('fecha_programada', models.DateField()),
                ('fecha_realizada', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField()),
                ('tecnico_responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('maquinaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.maquinaria')),
                ('repuestos', models.ManyToManyField(blank=True, to='core.repuesto')),
            ],
        ),
    ]
